INSERT INTO CFG (TMCODIGO, TIPO, NOME, PROPRIETARIO, NIVEL, VALOR, DESCRICAO, VALIDA) VALUES (0, 'TRIBUTO', 'ALIQUOTA CBS', 0, '2', '0', 'Aliquota do CBS, definda no ambito nacional', '<N4,2>');
UPDATE CFG SET VALOR = '0,9' WHERE TIPO = 'TRIBUTO' AND NOME = 'ALIQUOTA CBS';
INSERT INTO CFG (TMCODIGO, TIPO, NOME, PROPRIETARIO, NIVEL, VALOR, DESCRICAO, VALIDA) VALUES (0, 'TRIBUTO', 'ALIQUOTA IBS MUNICIPIO', 0, '2', '0', 'Aliquota do IBS padrão para o municipio, definda no ambito nacional', '<N4,2>');

ALTER TABLE ESTADO ADD TXALIQUOTAIBS NUMERIC(4,2) DEFAULT 0;
ALTER TABLE MUNICIPIO ADD TXALIQUOTAIBS NUMERIC(4,2) DEFAULT 0;
UPDATE ESTADO SET TXALIQUOTAIBS = 0.1;

CREATE TABLE CSTIBSCBS (
    ID                  CHAR(3) DEFAULT '000' NOT NULL,
    DESCRICAO           VARCHAR(50),
    TRIBUTACAO          CHAR(1) DEFAULT 'N',
    REDUCAO             CHAR(1) DEFAULT 'N',
    TRANSFCREDITO       CHAR(1) DEFAULT 'N',
    DIFERIMENTO         CHAR(1) DEFAULT 'N',
    MONOFASICA          CHAR(1) DEFAULT 'N',
    CREDITOPRESUMIDOZFM CHAR(1) DEFAULT 'N',
    AJUSTECREDITO       CHAR(1) DEFAULT 'N',
    CONSTRAINT CSTIBSCBSPK PRIMARY KEY (ID)
);

CREATE TABLE CLASSTRIB (
    ID                CHAR(6) DEFAULT '000000' NOT NULL,
    DESCRICAO         VARCHAR(180),
    TXREDIBS          NUMERIC(9,4) DEFAULT 0,
    TXREDCBS          NUMERIC(9,4) DEFAULT 0,
    REDUCAOBC         CHAR(1) DEFAULT 'N',
    TRIBREGULAR       CHAR(1) DEFAULT 'N',
    CREDITOPRESUMIDO  CHAR(1) DEFAULT 'N',
    ESTORNOCREDITO    CHAR(1) DEFAULT 'N',
    TIPOALIQUOTA      VARCHAR(40),
    DFEASSOCIADO      VARCHAR(120),
    ANEXO             SMALLINT DEFAULT 0,
    CONSTRAINT CLASSTRIBPK PRIMARY KEY (ID)
);

ALTER TABLE PRODUTO ADD CLASTRIBIBSCBS CHAR(6) DEFAULT '000000', ADD CLASTRIBIS CHAR(6) DEFAULT '000000';

ALTER TABLE NFCI ADD CLASTRIBIBSCBS CHAR(6) DEFAULT '000000',
                 ADD CLASTRIBIS CHAR(6) DEFAULT '000000';

ALTER TABLE NFC ADD TXIS NUMERIC(9,4) DEFAULT 0,
                ADD TXIBSUF NUMERIC(9,4) DEFAULT 0,
                ADD TXIBSMUN NUMERIC(9,4) DEFAULT 0,
                ADD TXCBS NUMERIC(9,4) DEFAULT 0;

CREATE TABLE NFCDCNFE (
    ID            BIGINT DEFAULT 0 NOT NULL,
    TIPODEBCRED   SMALLINT DEFAULT 0,
    ENTEGOV       SMALLINT DEFAULT 0,
    TXREDUTORGOV  NUMERIC(9,4) DEFAULT 0,
    OPERACAOGOV   SMALLINT DEFAULT 0,
    CONSTRAINT NFCDCNFEPK PRIMARY KEY (ID)
);

CREATE TABLE TIPODEBITOCREDITONFE (
    ID         SMALLINT DEFAULT 0 NOT NULL,
    DEBCRED    CHAR(1) DEFAULT 'D' NOT NULL,
    DESCRICAO  VARCHAR(100),
    CONSTRAINT TIPODEBITOCREDITONFEPK PRIMARY KEY (ID,DEBCRED)
);

INSERT INTO TIPODEBITOCREDITONFE (ID, DEBCRED, DESCRICAO) VALUES (1,'D','Transferência de créditos para Cooperativas');
INSERT INTO TIPODEBITOCREDITONFE (ID, DEBCRED, DESCRICAO) VALUES (2,'D','Anulação de Crédito por Saídas Imunes/Isentas');
INSERT INTO TIPODEBITOCREDITONFE (ID, DEBCRED, DESCRICAO) VALUES (3,'D','Débitos de notas fiscais não processadas na apuração');
INSERT INTO TIPODEBITOCREDITONFE (ID, DEBCRED, DESCRICAO) VALUES (4,'D','Multa e juros');
INSERT INTO TIPODEBITOCREDITONFE (ID, DEBCRED, DESCRICAO) VALUES (5,'D','Transferência de crédito na sucessão');
INSERT INTO TIPODEBITOCREDITONFE (ID, DEBCRED, DESCRICAO) VALUES (6,'D','Pagamento antecipado');
INSERT INTO TIPODEBITOCREDITONFE (ID, DEBCRED, DESCRICAO) VALUES (7,'D','Perda em estoque');
INSERT INTO TIPODEBITOCREDITONFE (ID, DEBCRED, DESCRICAO) VALUES (8,'D','Desenquadramento do SN');
INSERT INTO TIPODEBITOCREDITONFE (ID, DEBCRED, DESCRICAO) VALUES (1,'C','Multa e juros');
INSERT INTO TIPODEBITOCREDITONFE (ID, DEBCRED, DESCRICAO) VALUES (2,'C','Apropriação de crédito presumido de IBS sobre o saldo devedor na ZFM (art. 450, § 1º, LC 214/25)');
INSERT INTO TIPODEBITOCREDITONFE (ID, DEBCRED, DESCRICAO) VALUES (3,'C','Retorno por recusa na entrega ou por não localização do destinatário na tentativa de entrega');
INSERT INTO TIPODEBITOCREDITONFE (ID, DEBCRED, DESCRICAO) VALUES (4,'C','Redução de valores');
INSERT INTO TIPODEBITOCREDITONFE (ID, DEBCRED, DESCRICAO) VALUES (5,'C','Transferência de crédito na sucessão');
COMMIT WORK;

